For development we need install npm packages on the host OS
Inside ./webapp dir before docker compose up.

Fix tomorrownowapp_webapp_1 container launch error:

```
> webapp@0.1.0 start
> react-scripts start

node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- /home/node/.npm-global/lib/node_modules/react-scripts/scripts/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at Object.<anonymous> (/home/node/.npm-global/lib/node_modules/react-scripts/scripts/start.js:43:31)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/node/.npm-global/lib/node_modules/react-scripts/scripts/start.js'
  ]
}
```